### ISSUE TITLE
Invalid input response 

### ISSUE THREAD

**Issue by MPark988** [spencer741/GoogleRecaptchaV3Service#1]
Hi i create a sample api project in .net core using this code I am passing my site key as parameter in input and security key in apsetting.json like
{
  "recaptchaToken": "string"// here i am adding site key
}
but every time getting this error 
{
  "success": false,
  "error-codes": [
    "invalid-input-response"
  ]
}
my main purpose is to send this key from api to angular so need your help for this thank you.

**Comment by spencer741** [comment]
Hi @MPark988! Apologies for the wait. 

In AppSettings.json, you should be adding the secret key, not the site key.

<img width="787" alt="Screen Shot 2022-01-17 at 2 15 20 AM" src="https://user-images.githubusercontent.com/35856129/149732575-d0360473-67ac-4866-bf4c-9d362d75b6df.png">

The site key should be pasted in the leftmost text box when you load the app. The code I wrote injects the site key pasted in the browser to load the client side script and simulate normal reCaptcha workflow.

### Just to re-iterate:
**secret key** -> AppSettings.json

**site key** -> Text box in browser.

I just performed a fresh clone of the repo and did find/resolve a small bug that could have impacted other errors you might've been running into.

Test app is in working order.
